### ISSUE TITLE
Connect with Node-Red

### ISSUE THREAD

**Issue by nuiler** [vincedarley/homebridge-plugin-bwaspa#12]
I have successfully linked the Homebridge with Node-Red. Unfortunately, I still have problems with the control. 
I always get "error - invalid payload" What should the payload look like?
[flows.zip](https://github.com/vincedarley/homebridge-plugin-bwaspa/files/5897906/flows.zip)

**Comment by vincedarley** [comment]
This plugin connects bwaspas directly with homebridge. No node-red/mqtt or anything else involved.

So, I think you are better off asking your question somewhere else.

Speaking for myself, I did eventually manage to get the node-red/Balboa system working, but there was a lot of trial and error, and I long ago deleted that in favour of this plugin.
