### ISSUE TITLE
Spa Thermostat tile jumps to max heat when opened

### ISSUE THREAD

**Issue by iFixManyThings** [vincedarley/homebridge-plugin-bwaspa#16]
Whenever I tap this tile to open it in Apple Homekit, the spa temperature jumps to the max temp and begins heating.  I then must manually adjust the desired temp back down to where I had it.  Should it not just open and show current user-set temp?

**Comment by vincedarley** [comment]
I don't see this behaviour myself (which I agree would be wrong). Could you perhaps share a precise set of instructions for how you reproduce this, ideally with screenshots or similar?  Does it happen no matter what the desired temperature is?  And/or if you have set it to "low" or "high"?

**Comment by vincedarley** [comment]
Closing since no info for many months
