### ISSUE TITLE
Heat mode ready

### ISSUE THREAD

**Issue by cappadanna** [vincedarley/homebridge-plugin-bwaspa#19]
Hi, thanks for a great plugin. I have a button in the home app that says “Heat mode ready” but I can’t find any information about what it does?

**Comment by vincedarley** [comment]
That switches between "Ready" (=ON in homekit) and "Ready-in-Rest" (=OFF in
homekit) modes. See e.g. page 6 of this manual if you want to know more of
what that implies:
https://www.balboawatergroup.com/getdoc.cfm?id=1127#:~:text=Ready%2Din%2DRest%20Mode&text=It%20is%20assumed%20that%20the,will%20revert%20to%20Rest%20Mode
.

**Comment by cappadanna** [comment]
Great. Thank you!
