### ISSUE TITLE
"Balboa-Spa was not registered by any plugin." HOOBs Error

### ISSUE THREAD

**Issue by justinfanok** [vincedarley/homebridge-plugin-bwaspa#7]
Hello,

Great work on this plugin. I used it while I was running home bridge along with oznu's config-ui. I recently switched my setup to run in the HOOBS docker container for easier management, but it appears that it does not recognize that the plugin is registered? It's been hard to troubleshoot as I cannot seem to get much more information than the snippet below:
```
The requested platform "Balboa-Spa" was not registered by any plugin.
Your config.json is requesting the platform "Balboa-Spa" which has not been published by any installed plugins.

```

Any thoughts? 

Thanks

**Comment by vincedarley** [comment]
I've not used HOOBS at all, so honestly no idea. Perhaps try asking in the
discord homebridge plugin development channels?

**Comment by justinfanok** [comment]
I think I found the issue finally. The people who made the homebridge-lg-thinq-ac plugin used the same homebridge plugin template you did, and had the same issue. 
The plugin name needs to be part of the platform registration.


You can see their comments and file changes in the link below. Let me know if I can help by testing or modifying myself and submitting a merge request.



https://github.com/sman591/homebridge-lg-thinq-ac/pull/39


Thanks!

**Comment by vincedarley** [comment]
In 2.0.16 - thank you.
